name: Fly Deploy

on:
  push:
    branches:
      - CICD   # Se ejecuta solo en la rama CICD

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group    # Opcional: asegura que solo una acción se ejecute a la vez
    steps:
      - uses: actions/checkout@v4

    
      - name: Instalar dependencias
        run: npm install
      - name : correr test
        run: npm test

      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
